export const genre = [
    "Documentary",
    "Musical",
    "Fantasy",
    "Thriller",
    "War",
    "Animation",
    "Action",
    "Music",
    "Comedy",
    "Crime",
    "Romance",
    "Horror",
    "Film-Noir",
    "Drama",
    "Sci-Fi",
    "Sport",
    "Adventure",
    "Biography",
    "Mystery",
    "Short",
    "History",
    "Family",
    "Western"
]

export const year = [
    "2000",
    "2001",
    "2002",
    "2003",
    "2004",
    "2005",
    "2006",
    "2007",
    "2008",
    "2009",
    "2010",
    "2011",
    "2012",
    "2013",
    "2014",
    "2015",
]

export const countries = [
    "Hong Kong",
    "Ireland",
    "Greece",
    "Iceland",
    "Thailand",
    "Malaysia",
    "South Korea",
    "Belarus",
    "Brazil",
    "Vietnam",
    "Lithuania",
    "Sweden",
    "Iran",
    "France",
    "Papua New Guinea",
    "Tajikistan",
    "Martinique",
    "India",
    "Cambodia",
    "Trinidad and Tobago",
    "Tunisia",
    "Ghana",
    "Uganda",
    "Jamaica",
    "Congo",
    "Czech Republic",
    "Uruguay",
    "Isle Of Man",
    "Kuwait",
    "Somalia",
    "Brunei",
    "Afghanistan",
    "Finland",
    "Egypt",
    "Poland",
    "Liechtenstein",
    "Puerto Rico",
    "Germany",
    "Zaire",
    "Canada",
    "Albania",
    "Laos",
    "Mexico",
    "Qatar",
    "Uzbekistan",
    "Philippines",
    "Tanzania",
    "Botswana",
    "Faroe Islands",
    "Netherlands",
    "South Africa",
    "China",
    "Mongolia",
    "Indonesia",
    "Macao",
    "Peru",
    "Monaco",
    "Moldova",
    "Bermuda",
    "Hungary",
    "Venezuela",
    "Haiti",
    "Estonia",
    "USA",
    "Russia",
    "Croatia",
    "North Korea",
    "Serbia",
    "Czechoslovakia",
    "El Salvador",
    "Spain",
    "Chad",
    "Greenland",
    "Armenia",
    "Italy",
    "Morocco",
    "Taiwan",
    "Austria",
    "Micronesia",
    "Belgium",
    "Yugoslavia",
    "Slovenia",
    "Angola",
    "Rwanda",
    "Gabon",
    "Guatemala",
    "Saudi Arabia",
    "Paraguay",
    "Burma",
    "Kyrgyzstan",
    "Australia",
    "Cyprus",
    "Burkina Faso",
    "Mali",
    "Cète d'Ivoire",
    "Cameroon",
    "Bahamas",
    "Samoa",
    "Dominican Republic",
    "Kazakhstan",
    "Denmark",
    "Kenya",
    "Georgia",
    "Norway",
    "Syria",
    "Zimbabwe",
    "Republic of Macedonia",
    "Ukraine",
    "Japan",
    "Bangladesh",
    "Panama",
    "West Germany",
    "UK",
    "Malta",
    "Luxembourg",
    "Palestine",
    "Chile",
    "Nepal",
    "Aruba",
    "Bolivia",
    "East Germany",
    "Serbia and Montenegro",
    "Sri Lanka",
    "Portugal",
    "Costa Rica",
    "The Democratic Republic Of Congo",
    "Slovakia",
    "Madagascar",
    "Iraq",
    "Bosnia and Herzegovina",
    "Jordan",
    "Latvia",
    "Ecuador",
    "Montenegro",
    "Vanuatu",
    "Ethiopia",
    "Kosovo",
    "New Zealand",
    "Soviet Union",
    "Liberia",
    "Israel",
    "Colombia",
    "Switzerland",
    "Cuba",
    "Argentina",
    "United Arab Emirates",
    "Bulgaria",
    "Turkey",
    "Lebanon"
]

export const languages = [
    "English",
    "Mandarin",
    "Dutch",
    "Hindi",
    "Norwegian",
    "Thai",
    "Kazakh",
    "Chinese",
    "Armenian",
    "French",
    "Italian",
    "Spanish",
    "Japanese",
    "Turkish",
    "Swedish",
    "Czech",
    "Russian",
    "German",
    "Spanish",
]
